// ui/src/lib/blur-hash/BlurImage.vue
<template>
  <div :class="['relative transition-all duration-500']">
    <TransitionGroup
      mode="in-out"
      name="fade"
      :class="['absolute bottom-0 left-0 right-0 top-0 h-full w-full', 'transition-group-for-blur']"
    >
      <BlurHashCanvas
        v-show="!isLoaded"
        :hash="hash"
        :width="width"
        :height="height"
        :punch="punch"
        key="canvas"
        :class="['absolute bottom-0 left-0 right-0 top-0 h-full w-full', 'canvas-for-blur']"
      />
      <img
        v-show="isLoaded"
        v-bind="$attrs"
        key="image"
        :class="['absolute bottom-0 left-0 right-0 top-0 h-full w-full', 'image-for-blur']"
        :src="src"
        :srcset="srcset"
        @load="isLoaded = true"
      />
    </TransitionGroup>
  </div>
</template>

<script setup lang="ts">
import { computed, defineOptions, ref } from 'vue';
import BlurHashCanvas, { type BlurCanvasProps } from './BlurCanvas.vue';

// Use custom options to bind image props to not-the-parent.
defineOptions({ inheritAttrs: false });

export interface BlurHashProps extends BlurCanvasProps {
  src?: string;
  srcset?: string;
  transitionDuration?: number;
}
const props = defineProps<BlurHashProps>();
const hasImage = computed(() => !!(props.src || props.srcset));

const isLoaded = ref(false);
</script>

// unsplashjs-react/src/components/BlurImage.tsx
import { useRef } from 'react';
import classNames from 'classnames';
import { Transition } from '@headlessui/react';
import BlurCanvas, { BlurCanvasProps } from './BlurCanvas';

export interface BlurHashProps extends BlurCanvasProps {
  src?: string;
  srcset?: string;
  transitionDuration?: number;
}

export const BlurImage = ({
  hash,
  height,
  width,
  punch,
  src,
  srcset,
  transitionDuration,
  ...rest
}: React.HTMLAttributes<HTMLImageElement> & BlurHashProps) => {
  const isLoaded = useRef(false);

  return (
    <div className="relative transition-all duration-500">
      <Transition
        as="div"
        className="transition-group-for-blur inset absolute h-full w-full"
      >
        <BlurCanvas
          className={classNames(
            'canvas-for-blur',
            'transition duration-300 ease-in data-[closed]:opacity-0',
            'inset absolute h-full w-full',
            {
              hidden: isLoaded,
            }
          )}
          hash={hash}
          width={width}
          height={height}
          punch={punch}
        />
        <img
          className={classNames(
            'image-for-blur',
            'transition duration-300 ease-in data-[closed]:opacity-0',
            'inset absolute h-full w-full',
            {
              hidden: !isLoaded,
            }
          )}
          src={src}
          srcSet={srcset}
          onLoad={() => (isLoaded.current = true)}
          {...rest}
        />
      </Transition>
    </div>
  );
};
export default BlurImage;
